#pragma once
#include "Database.h"
#include "Screen.h"

namespace DatabaseSide
{
	enum DatabaseMenuChoices
	{
		ADMINCONTROL = 1, STOCKCONTROL, MEALCONTROL, ORDERCONTROL, NOTIFICATIONCONTROL, TABLECONTROL
	};

	enum ADMINCHOICES
	{
		SHOWALLADMIN = 1, SHOWADMIN, ADDADMIN, DELADMIN, UPDATEADMIN
	};
	enum STOCKCHOICES
	{
		SHOWALLING = 1, SHOWING, ADDING, UPDATEING, DELETEING, INCREASEINGAMOUNT, DECREASEINGAMOUNT
	};
	enum MEALCHOICES
	{
		SHOWALLMEAL = 1, SHOWMEAL, ADDMEAL, DELMEAL, DELALLMEAL, UPDATEMEAL, ADDINGTOMEAL, DELINGFRMMEAL
	};
	class DatabaseSide
	{
	public:
		static void start(Database & db);
	};
}